version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - docker.env
    ports:
      - 3000:3000
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - mysql
    tty: true
    stdin_open: true
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: "jobportal"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "123.456"
    expose:
      - 3306
